version: '3.8'

services:
  kafka:
    image: bitnami/kafka:latest
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ENABLE_KRAFT=yes
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093,EXTERNAL://localhost:9094
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true

  tika:
    image: apache/tika:3.2.1.0-full
    hostname: tika
    container_name: tika
    ports:
      - "9998:9998"

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    container_name: pdf-producer
    depends_on:
      - kafka
    volumes:
      - ./test_pdfs:/app/pdfs:ro
    environment:
      - KAFKA_BROKERS=kafka:9092
    stdin_open: true
    tty: true

  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    container_name: pdf-consumer
    depends_on:
      - kafka
      - tika
    volumes:
      - ./test_pdfs:/app/pdfs:ro
    environment:
      - KAFKA_BROKERS=kafka:9092
      - TIKA_URL=http://tika:9998
